"""add_product_tables

Revision ID: 6a20075815bd
Revises: 4da4206958b9
Create Date: 2026-01-12 19:51:50.881207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a20075815bd'
down_revision: Union[str, None] = '4da4206958b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_mappings',
    sa.Column('mapping_id', sa.UUID(), nullable=False, comment='映射ID'),
    sa.Column('ali_product_code', sa.String(length=100), nullable=False, comment='阿里云产品代码'),
    sa.Column('competitor_name', sa.String(length=50), nullable=False, comment='竞品厂商'),
    sa.Column('comp_product_code', sa.String(length=100), nullable=False, comment='竞品产品代码'),
    sa.Column('mapping_type', sa.String(length=50), nullable=True, comment='映射类型'),
    sa.Column('confidence_score', sa.String(length=5), nullable=True, comment='映射置信度'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建方式'),
    sa.PrimaryKeyConstraint('mapping_id'),
    comment='竞品映射表'
    )
    op.create_index(op.f('ix_competitor_mappings_ali_product_code'), 'competitor_mappings', ['ali_product_code'], unique=False)
    op.create_index('ix_mapping_ali_competitor', 'competitor_mappings', ['ali_product_code', 'competitor_name'], unique=False)
    op.create_table('product_prices',
    sa.Column('price_id', sa.UUID(), nullable=False, comment='价格记录ID'),
    sa.Column('product_code', sa.String(length=100), nullable=False, comment='产品代码'),
    sa.Column('region', sa.String(length=50), nullable=False, comment='地域'),
    sa.Column('spec_type', sa.String(length=100), nullable=True, comment='规格类型'),
    sa.Column('billing_mode', sa.String(length=50), nullable=False, comment='计费模式'),
    sa.Column('unit_price', sa.String(length=20), nullable=False, comment='单价'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('pricing_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='定价变量'),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False, comment='生效日期'),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True, comment='失效日期'),
    sa.PrimaryKeyConstraint('price_id'),
    comment='产品价格表'
    )
    op.create_index('ix_price_product_region', 'product_prices', ['product_code', 'region'], unique=False)
    op.create_index(op.f('ix_product_prices_product_code'), 'product_prices', ['product_code'], unique=False)
    op.create_table('product_specs',
    sa.Column('spec_id', sa.UUID(), nullable=False, comment='规格ID'),
    sa.Column('product_code', sa.String(length=100), nullable=False, comment='产品代码'),
    sa.Column('spec_name', sa.String(length=100), nullable=False, comment='规格名称'),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='规格值'),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='约束条件'),
    sa.PrimaryKeyConstraint('spec_id'),
    comment='产品规格配置表'
    )
    op.create_index(op.f('ix_product_specs_product_code'), 'product_specs', ['product_code'], unique=False)
    op.create_table('products',
    sa.Column('product_code', sa.String(length=100), nullable=False, comment='产品代码'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='产品名称'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='产品类别'),
    sa.Column('vendor', sa.String(length=50), nullable=False, comment='厂商'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品描述'),
    sa.Column('description_vector', sa.Text(), nullable=True, comment='描述向量(文本存储)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('product_code'),
    comment='产品主表'
    )
    op.create_index('ix_product_category_vendor', 'products', ['category', 'vendor'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('ix_product_category_vendor', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_specs_product_code'), table_name='product_specs')
    op.drop_table('product_specs')
    op.drop_index(op.f('ix_product_prices_product_code'), table_name='product_prices')
    op.drop_index('ix_price_product_region', table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index('ix_mapping_ali_competitor', table_name='competitor_mappings')
    op.drop_index(op.f('ix_competitor_mappings_ali_product_code'), table_name='competitor_mappings')
    op.drop_table('competitor_mappings')
    # ### end Alembic commands ###
